### PR TITLE
fix: Blank page

### LINKED ISSUE #10: Blank page
I have entered my github user name in the field and after hitting the generate button I got this blank page
image

And in console log I have got this error.

image

### PR DESCRIPTION
**Pull request by Hat52**
The blank page bug fixed closes #10.

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@Hat52 , It would be great if you can attach the screen recording or something.

File: src/components/GithubPopularRepositories.tsx [hunk 1]
```diff
@@ -23,8 +23,9 @@ const GithubPopularRepositories: FC<Props> = ({ repositories }) => {
           md: 'repeat(2, 1fr)',
         }}
       >
-        {repositories.map((repository) => (
-          <Link
+        {repositories.map((repository) => {
+          if(!Object.keys(repository).length) return <></>
```
Comment (Sachin-chaurasiya) [inline src/components/GithubPopularRepositories.tsx:27]: This is to avoid negative conditions and performant checks.

```suggestion
          if(Object.entries(repository).length === 0) return <></>
```

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]

File: src/components/GithubPopularRepositories.tsx (hunk 1 above)
Comment (Hat52) [reply src/components/GithubPopularRepositories.tsx]: Fixed

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
Great work @Hat52  🙌🏻,
Thanks for the contributions ✨

**Comment by Sachin-chaurasiya** [comment]
@all-contributors please add @Hat52  for Code
