### PR TITLE
fix: guard against null primary language in popular repositories

### LINKED ISSUE #78: [Bug]: Certain valid GitHub usernames cause runtime error despite successful API responses
### What happened?

 When entering some valid GitHub usernames on the site, the page crashes and shows a 404 screen with the following error:  

Image

Steps to Reproduce
- Visit: https://ygc.sachinchaurasiya.dev/
- Enter the GitHub username laxitajain
- Submit

### Please provide an bug screenshot

_No response_

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by laxitajain**
## Pull Request Checklist

Before submitting a pull request, please make sure that your changes meet the following criteria:

- [x] Ensure that your code adheres to our coding conventions and is properly formatted.
- [x] Test your changes extensively to ensure that they do not introduce any new bugs.
- [x] Confirm that you agree to the code of conduct.

## Related Issues

fixes #78 

## Description

GitHub’s GraphQL API may return primaryLanguage: null for pinned repositories.
The current UI assumes this field is always present, which can lead to a runtime crash when rendering popular repositories.

This PR adds defensive checks to make the component resilient to such cases, without changing existing behavior.

- Added a null guard around primaryLanguage before accessing its properties
- Added a safety check to ensure repositories exists before rendering
- No changes to API calls, data flow, or UI behavior otherwise

This now prevents runtime crashes in GithubPopularRepositories, leading to the displayed TypeError.

## Screenshots

Before: 
image
After:
image

### CODE REVIEW

File: src/components/GithubPopularRepositories.tsx [hunk 1]
```diff
@@ -6,68 +6,77 @@ import { GoRepo } from 'react-icons/go';
 import { getIconByLanguage } from 'utils/iconUtils';
 
 interface Props {
-  repositories: PinnedItemNode[];
+  repositories?: PinnedItemNode[];
```
Comment (Sachin-chaurasiya) [inline src/components/GithubPopularRepositories.tsx]: We don't need to make this optional. instead, have the default value as an empty list

File: src/components/GithubPopularRepositories.tsx [hunk 2]
```diff
@@ -6,68 +6,77 @@ import { GoRepo } from 'react-icons/go';
...
         templateColumns={{
           base: 'repeat(1, 1fr)',
           md: 'repeat(2, 1fr)',
-        }}
-      >
+        }}>
         {repositories.map((repository) => {
-          if (Object.entries(repository).length === 0) {
-            return <></>;
+          if (!repository || !repository.url) {
```
Comment (Sachin-chaurasiya) [inline src/components/GithubPopularRepositories.tsx]: We should filter out the invalid or null repositories before rendering them.

File: src/components/GithubPopularRepositories.tsx [hunk 3]
```diff
@@ -6,68 +6,77 @@ import { GoRepo } from 'react-icons/go';
...
-                    : 'gray.100',
+                  colorMode === 'dark' ? 'whiteAlpha.200' : 'gray.100',
+                textDecoration: 'none',
               }}
               border="1px"
               borderColor="gray.200"
               borderRadius="4px"
               href={repository.url}
-              key={repository.name}
+              key={repository.nameWithOwner}
```
Comment (Sachin-chaurasiya) [inline src/components/GithubPopularRepositories.tsx:47]: Why are we making this change?

Comment (laxitajain) [reply src/components/GithubPopularRepositories.tsx:47]: Although we currently render repositories for a single user, nameWithOwner is a more reliable unique key and helps prevent potential collisions if this component is reused in the future.

Comment (laxitajain) [reply src/components/GithubPopularRepositories.tsx:47]: I've implemented the other changes.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
Great work @laxitajain 🙌🏻,
Thanks for the contributions ✨

**Comment by laxitajain** [comment]
hey @Sachin-chaurasiya, if my PR fits the requirements, could you please ask the all-contributors bot to add me?

**Comment by Sachin-chaurasiya** [comment]
@all-contributors please add @laxitajain for Code
